/**
 * Taiyabah Masjid — one sūrah at a time, not the whole muṣḥaf.
 * Copyright (c) 2026 Yameen Bux. All rights reserved. See LICENSE.md.
 *
 * quran-text.json is 2.29MB of JSON and it was `require`d whole to read any
 * one sūrah. The require sits inside a useMemo, so it does not run at startup
 * — but the first time anybody opens ANY sūrah, the JavaScript thread parses
 * all 114 of them, and the UI is frozen while it does. That is the stutter on
 * opening the muṣḥaf.
 *
 * The median sūrah is 10KB. Al-Fātiḥah is 391 bytes. Even al-Baqarah, the
 * longest in the Qurʼan, is 174KB — thirteen times less than the whole.
 *
 * Metro cannot resolve `require("../data/quran/" + n + ".json")`, because it
 * builds its graph statically and a computed path is not a graph edge. So the
 * generated index is 114 explicit requires, each wrapped in an arrow function
 * so that none of them runs until it is called. Metro sees every edge and
 * bundles every sūrah; the device parses exactly one.
 *
 *   node scripts/split-quran.mjs
 */
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const SRC = path.join(root, "src/data/quran-text.json");
const DIR = path.join(root, "src/data/quran");
const INDEX = path.join(root, "src/data/quran-index.js");

const all = JSON.parse(fs.readFileSync(SRC, "utf8"));
const numbers = Object.keys(all).map(Number).sort((a, b) => a - b);
if (numbers.length !== 114) {
  console.error(`expected 114 sūrahs, found ${numbers.length} — refusing to split`);
  process.exit(1);
}

fs.rmSync(DIR, { recursive: true, force: true });
fs.mkdirSync(DIR, { recursive: true });

let ayat = 0;
for (const n of numbers) {
  const verses = all[String(n)];
  ayat += verses.length;
  /* No pretty-printing: this is data a phone parses, not prose anybody reads,
     and the whitespace would be a megabyte of nothing. */
  fs.writeFileSync(path.join(DIR, `${n}.json`), JSON.stringify(verses));
}

const lines = numbers.map(n => `  ${n}: () => require("./quran/${n}.json"),`).join("\n");
fs.writeFileSync(INDEX, `/* GENERATED by scripts/split-quran.mjs — do not edit by hand.
 *
 * One entry per sūrah, each a FUNCTION so the require inside it does not run
 * until that sūrah is opened. Metro needs every path spelled out to see the
 * edge; the device needs only the one it calls.
 */
const SURAH = {
${lines}
};

/* The verses of one sūrah: [[ayah, arabic, english], ...], or [] if asked for
 * a number that is not 1-114. */
export function surah(n) {
  const load = SURAH[n];
  return load ? load() : [];
}
`);

const sizes = numbers.map(n => fs.statSync(path.join(DIR, `${n}.json`)).size);
const whole = fs.statSync(SRC).size;
console.log(`${numbers.length} sūrahs, ${ayat} āyāt`);
console.log(`was:  one file, ${Math.round(whole / 1024)}KB, parsed to read any verse`);
console.log(`now:  largest ${Math.round(Math.max(...sizes) / 1024)}KB, ` +
            `median ${Math.round(sizes.sort((a, b) => a - b)[Math.floor(sizes.length / 2)] / 1024)}KB, ` +
            `smallest ${Math.min(...sizes)} bytes`);
