#!/usr/bin/env node
/* Build lang/ur.js, lang/gu.js and lang/ar.js from lang/src/*.json.
 *
 * One source, three packs. A key added to the source appears in all three or
 * the coverage check fails it, so the packs cannot quietly drift apart — which
 * is how a screen ends up half-translated with nobody noticing.
 *
 * Each entry is  "key": [Urdu, Gujarati, Arabic].
 *
 * The marker " keep" means leave the English exactly as it is. That is for
 * proper nouns, the society's registered name, bank names and account details:
 * translating a bank's name helps nobody, and makes details harder to check
 * against a statement.
 *
 *   node scripts/build-lang.mjs
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";

const LANGS = [
  { code: "ur", i: 0, name: "اردو",     nameEn: "Urdu",     dir: "rtl" },
  { code: "gu", i: 1, name: "ગુજરાતી",   nameEn: "Gujarati", dir: "ltr" },
  { code: "ar", i: 2, name: "العربية",   nameEn: "Arabic",   dir: "rtl" },
];

const KEEP = " keep";

/* The English each key stands for, read from the markup — so a "keep" entry
   renders the real English rather than a placeholder. */
const html = readFileSync("index.html", "utf8");
const decode = s => s
  .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&middot;/g, "·")
  .replace(/&hellip;/g, "…").replace(/&mdash;/g, "—").replace(/&ndash;/g, "–")
  .replace(/&rsquo;/g, "’").replace(/&lsquo;/g, "‘")
  .replace(/&ldquo;/g, "“").replace(/&rdquo;/g, "”")
  .replace(/&nbsp;/g, " ").replace(/&times;/g, "×").replace(/&rsaquo;/g, "›")
  .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)));
const english = {};
for (const m of html.matchAll(/data-i18n="([^"]+)"[^>]*>([^<>]+)</g))
  english[m[1]] = decode(m[2]).replace(/\s+/g, " ").trim();

/* Read every chunk. Splitting the source by area keeps a 350-entry table
   reviewable; a duplicate key across chunks is a mistake, so say so. */
const table = {};
for (const f of readdirSync("lang/src").filter(f => f.endsWith(".json")).sort()) {
  const part = JSON.parse(readFileSync(`lang/src/${f}`, "utf8"));
  for (const [k, v] of Object.entries(part)) {
    if (k.startsWith("_")) continue;
    if (k in table) throw new Error(`${k} is defined twice — second time in ${f}`);
    if (!Array.isArray(v) || v.length !== 3)
      throw new Error(`${k} in ${f} must be [urdu, gujarati, arabic]`);
    table[k] = v;
  }
}

for (const lang of LANGS) {
  const strings = {};
  for (const [key, vals] of Object.entries(table)) {
    const v = vals[lang.i];
    strings[key] = v === KEEP ? (english[key] ?? key) : v;
  }
  const body =
    `/**\n` +
    ` * Taiyabah Masjid — ${lang.nameEn} language pack\n` +
    ` * Copyright (c) 2026 Yameen Bux. All rights reserved. See LICENSE.md.\n` +
    ` *\n` +
    ` * GENERATED by scripts/build-lang.mjs from lang/src/*.json — edit those.\n` +
    ` *\n` +
    ` * ⚠ NOT YET REVIEWED BY A NATIVE SPEAKER. Islamic terminology in\n` +
    ` * particular should be confirmed by someone from the community before this\n` +
    ` * pack is treated as final. Any key missing here falls back to English\n` +
    ` * rather than showing a blank.\n` +
    ` *\n` +
    ` * Loaded only when a user selects this language — never in the main bundle.\n` +
    ` */\n` +
    `window.LANG_PACK = ${JSON.stringify({
      code: lang.code, name: lang.name, nameEn: lang.nameEn, dir: lang.dir, strings,
    }, null, 1)};\n`;
  writeFileSync(`lang/${lang.code}.js`, body);
  console.log(`lang/${lang.code}.js — ${Object.keys(strings).length} strings`);
}
