/* GENERATED by scripts/extract-madrasah.mjs — do not edit.
 *
 * The madrasah's year, lifted verbatim from the website's index.html, which is
 * where it is edited once a year. Re-run the script after it changes there.
 */
export const MAD_YEAR = { from:"2026-09-01", to:"2027-08-31" };

export const MAD_CLOSURES = [
  { id:"insert",    name:"Insert Day",        note:"Teachers in \u2014 no students", from:"2026-09-01", to:"2026-09-01" },
  { id:"autumnht",  name:"Half Term Break",   note:"",                               from:"2026-10-26", to:"2026-10-30" },
  { id:"christmas", name:"End of Term Break", note:"Christmas and New Year",         from:"2026-12-21", to:"2027-01-01" },
  { id:"ramadhan",  name:"Ramadhan Holidays", note:"Ramadhan and Eid al-Fitr",       from:"2027-02-08", to:"2027-03-12" },
  { id:"springht",  name:"End of Term Break", note:"",                               from:"2027-03-26", to:"2027-04-02" },
  { id:"eidadha",   name:"Eid al-Adha",       note:"Eid holidays",                   from:"2027-05-17", to:"2027-05-18" },
  { id:"summerht",  name:"Summer Half Term",  note:"",                               from:"2027-05-31", to:"2027-06-04" },
  { id:"endofyear", name:"End of Year",       note:"Summer holidays",                from:"2027-07-26", to:"2027-09-03" }
];

export const MAD_EVENTS = [
  { id:"mawlid",    name:"Mawlid an-Nabi \uFDFA", sub:"12 Rabi\u02BF al-Awwal", on:"2026-08-25" },
  { id:"miraj",     name:"Laylat al-Mi\u02BFraj",  sub:"27 Rajab",            on:"2027-01-05" },
  { id:"baraah",    name:"Laylat al-Bara\u02BEah", sub:"15 Sha\u02BFban",     on:"2027-01-23" },
  { id:"ramadan1",  name:"Ramadhan begins",       sub:"1 Ramadhan",          on:"2027-02-08" },
  { id:"lastten",   name:"Last ten nights begin", sub:"21 Ramadhan",         on:"2027-02-28" },
  { id:"eidfitr",   name:"Eid al-Fitr",           sub:"1 Shawwal",           on:"2027-03-09" },
  { id:"arafah",    name:"Day of Arafah",         sub:"9 Dhul Hijjah",       on:"2027-05-15" },
  { id:"eidadha",   name:"Eid al-Adha",           sub:"10 Dhul Hijjah",      on:"2027-05-16" },
  { id:"newyear",   name:"Islamic New Year",      sub:"1 Muharram 1449",     on:"2027-06-06" },
  { id:"ashura",    name:"Day of \u02BFAshura",    sub:"10 Muharram",         on:"2027-06-15" }
];
