/* GENERATED by scripts/extract-reminders.mjs — do not edit.
 *
 * The home screen's reminders, copied out of the web app's index.html as
 * source so the two cannot disagree about when the white days fall or when the
 * last hour of Jumuʿah is. Edit them there and run the script again.
 */

/* num() and hm12() are the web app's own formatters; the native equivalents
 * are passed in beside the translator. */
const MARK_MAWLID = false;
const suhoorNote = c => c.suhoor
  ? " " + T("reminder.suhoor_ends","Suhūr ends {time}.").replace("{time}", PRETTY((c.suhoor)))
  : "";
const hIs = (c, day, month) => c.hDay===day && new RegExp(month,"i").test(c.hMonth);
const tIs = (c, day, month) => c.tDay===day && new RegExp(month,"i").test(c.tMonth);

const CALENDAR_DAYS = [
  /* --- nights: these begin at Maghrib the evening before --- */
  { id:"meraj-eve", ar:"شَبِ مِعْرَاج", t:"Shab-e-Miʿrāj tonight",
    d:"The night of 27 Rajab begins after Maghrib this evening.",
    when:c => tIs(c,27,"Rajab") },
  { id:"meraj", ar:"شَبِ مِعْرَاج", t:"Shab-e-Miʿrāj",
    d:"27 Rajab — the Night Journey and Ascension.",
    when:c => hIs(c,27,"Rajab") },
  { id:"baraat-eve", ar:"شَبِ بَرَاءَت", t:"Shab-e-Barāʾat tonight",
    d:"The night of 15 Shaʿbān begins after Maghrib this evening.",
    when:c => tIs(c,15,"Sha") },
  { id:"baraat", ar:"شَبِ بَرَاءَت", t:"Shab-e-Barāʾat",
    d:"15 Shaʿbān — a night many spend in worship and duʿā.",
    when:c => hIs(c,15,"Sha") },

  /* --- Eid --- */
  { id:"fitr-eve", ar:"عِيدُ الْفِطْر", t:"Eid al-Fitr tomorrow",
    d:"Eid salah times are announced by the masjid. Fitrana should be given before the salah.",
    when:c => tIs(c,1,"Shawwal") },
  { id:"fitr", ar:"عِيدُ الْفِطْر", t:"Eid al-Fitr",
    d:"Eid Mubarak. Eid salah times are announced by the masjid.",
    when:c => hIs(c,1,"Shawwal") },
  { id:"adha-eve", ar:"عِيدُ الْأَضْحَىٰ", t:"Eid al-Adha tomorrow",
    d:"10 Dhul Hijjah falls tomorrow. Eid salah times are announced by the masjid.",
    when:c => tIs(c,10,"Hijjah") },
  { id:"adha", ar:"عِيدُ الْأَضْحَىٰ", t:"Eid al-Adha",
    d:"Eid Mubarak. Qurbani follows the Eid salah.",
    when:c => hIs(c,10,"Hijjah") },

  /* --- Hajj season --- */
  { id:"hajj", ar:"أَيَّامُ الْحَجّ", t:"The days of Hajj",
    d:"8th to 12th Dhul Hijjah.",
    when:c => /Hijjah/i.test(c.hMonth) && c.hDay>=8 && c.hDay<=12 },

  /* --- Muharram --- */
  { id:"newyear", ar:"رَأْسُ السَّنَةِ الْهِجْرِيَّة", t:"Islamic New Year",
    d:"1 Muharram — the start of the Hijri year.",
    when:c => hIs(c,1,"Muharram") },

  /* --- Ramadan's final third --- */
  { id:"lastten", ar:"الْعَشْرُ الْأَوَاخِر", t:"The last ten nights",
    d:"Laylat al-Qadr is sought in the odd nights of the final ten.",
    when:c => /Ramadan/i.test(c.hMonth) && c.hDay>=21 },

  /* --- 27 Safar --- */
  { id:"hijrah", ar:"الْهِجْرَة", t:"The Hijrah",
    d:"27 Safar — the Prophet ﷺ set out for Madinah.",
    when:c => hIs(c,27,"Safar") },

  /* --- optional, off by default (see MARK_MAWLID above) --- */
  { id:"mawlid", ar:"رَبِيعُ الْأَوَّل", t:"12 Rabiʿ al-Awwal",
    d:"A date noted in the Islamic calendar.",
    when:c => MARK_MAWLID && hIs(c,12,"Rabi al-Awwal") },
];
const REMINDERS = [
  ...CALENDAR_DAYS,
  /* --- heads-up for tomorrow: these need a decision tonight --- */
  { id:"ramadan-eve", ar:"رَمَضَان", t:"Ramadan begins tomorrow",
    d:c=>T("reminder.ramadan-eve.d","The first fast is tomorrow.") + suhoorNote(c)
         + " " + T("reminder.ramadan-eve.d2","Taraweeh follows Isha jamāʿah."),
    when:c => /Ramadan/i.test(c.tMonth) && c.tDay===1 },
  { id:"arafah-eve", ar:"يَوْمُ عَرَفَة", t:"Day of ʿArafah is tomorrow",
    d:c=>T("reminder.arafah-eve.d","The 9th of Dhul Hijjah falls tomorrow — a day of voluntary fasting.") + suhoorNote(c),
    when:c => /Hijjah/i.test(c.tMonth) && c.tDay===9 },
  { id:"ashura-eve", ar:"يَوْمُ عَاشُورَاء", t:"ʿĀshūrāʾ fasting tomorrow",
    d:c=>T("reminder.ashura-eve.d","Many fast the 9th and 10th of Muharram.") + suhoorNote(c),
    when:c => /Muharram/i.test(c.tMonth) && (c.tDay===9 || c.tDay===10) },
  { id:"beed-eve", ar:"الْأَيَّامُ الْبِيض", t:"Optional fasting tomorrow",
    d:c=>T("reminder.beed-eve.d","Tomorrow is one of the white days — the 13th, 14th and 15th of the Islamic month.") + suhoorNote(c),
    when:c => [13,14,15].includes(c.tDay) },
  { id:"monthu-eve", ar:"صِيَامُ الِاثْنَيْنِ وَالْخَمِيس", t:"Optional fasting tomorrow",
    d:c=>T("reminder.monthu-eve.d","Tomorrow is {day} — a day many keep a voluntary fast.")
         .replace("{day}", fullDow(c.tDow===1?1:4)) + suhoorNote(c),
    when:c => c.tDow===1 || c.tDow===4 },

  /* --- expiring soon --- */
  { id:"jumuah-hour", ar:"سَاعَةُ الْإِجَابَة", t:"The last hour of Jumuʿah",
    d:"The final part of Friday, before Maghrib, is sought for duʿā.",
    when:c => c.dow===5 && c.live && c.afterAsr && c.beforeMaghrib },
  { id:"morning", ar:"أَذْكَارُ الصَّبَاح", t:"Morning adhkār",
    d:"The window after Fajr until sunrise.",
    when:c => c.live && c.afterFajr && c.beforeSunrise },
  { id:"evening", ar:"أَذْكَارُ الْمَسَاء", t:"Evening adhkār",
    d:"From after Asr until Maghrib.",
    when:c => c.live && c.afterAsr && c.beforeMaghrib },

  /* --- today --- */
  { id:"ramadan", ar:"رَمَضَان", t:"Ramadan",
    d:"Suhūr ends 10 minutes before Fajr begins. Taraweeh follows Isha jamāʿah.",
    when:c => /Ramadan/i.test(c.hMonth) },
  { id:"arafah", ar:"يَوْمُ عَرَفَة", t:"Day of ʿArafah",
    d:"The 9th of Dhul Hijjah.",
    when:c => /Hijjah/i.test(c.hMonth) && c.hDay===9 },
  { id:"ashura", ar:"يَوْمُ عَاشُورَاء", t:"Day of ʿĀshūrāʾ",
    d:"The 10th of Muharram — a day of voluntary fasting.",
    when:c => /Muharram/i.test(c.hMonth) && (c.hDay===9 || c.hDay===10) },
  { id:"tenhijjah", ar:"عَشْرُ ذِي الْحِجَّة", t:"The first ten days of Dhul Hijjah",
    d:"A time for extra dhikr, fasting and good deeds.",
    when:c => /Hijjah/i.test(c.hMonth) && c.hDay<=9 },
  { id:"beed", ar:"الْأَيَّامُ الْبِيض", t:"The white days",
    d:"The 13th, 14th and 15th of the Islamic month — days of voluntary fasting.",
    when:c => [13,14,15].includes(c.hDay) },
  { id:"monthu", ar:"صِيَامُ الِاثْنَيْنِ وَالْخَمِيس", t:"Monday & Thursday fasting",
    d:"A voluntary fast many keep through the year.",
    when:c => c.dow===1 || c.dow===4 },

  /* --- Friday, all day --- */
  { id:"kahf", ar:"سُورَةُ الْكَهْف", t:"Sūrah al-Kahf",
    d:"Many read it on Fridays — from Maghrib on Thursday through to Maghrib on Friday.",
    when:c => c.dow===5 },
  { id:"salawat", ar:"اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّد", t:"Salawāt upon the Prophet ﷺ",
    d:"Fridays are a time to send salawāt often.",
    when:c => c.dow===5 },

  /* --- evergreen --- */
  { id:"kursi", ar:"آيَةُ الْكُرْسِيّ", t:"Āyat al-Kursī",
    d:"Recited after each fard salah.",
    when:c => true },
  { id:"iqamah", ar:"الدُّعَاءُ بَيْنَ الْأَذَانِ وَالْإِقَامَة", t:"Duʿā before jamāʿah",
    d:"The time between the adhān and the iqāmah is a time for duʿā.",
    when:c => true },
];

/* The translator is passed in rather than reached for: these definitions were
 * written against a global t() the web app has and this app does not. */
let T = (k, en) => en;
let PRETTY = x => x;
export function setReminderTranslator(fn, pretty) { T = fn; if (pretty) PRETTY = pretty; }

/* The web app's own helpers, which these definitions close over. */
const DOW = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
function fullDow(n) { return T("date.fulldow." + n, DOW[n]); }

export { REMINDERS };
