/* Taiyabah Masjid — everyday duʿās
   Copyright (c) 2026 Yameen Bux. All rights reserved. See LICENSE.md.

   Built for someone learning: each duʿā carries the Arabic, a transliteration
   to read from until the Arabic is fluent, a plain English meaning, and the
   collection it comes from.

   Wording varies between narrations and printings. This set should be
   confirmed with the imam before it is treated as settled — the page says so.

   Loaded only when the Duʿās page is opened. */
window.DUAS = {
  reviewNote: "Wording varies between narrations and printings. Confirm with the imam before treating this as settled.",
  categories: [

    { id: "day", title: "Through the Day", icon: "sun", items: [
      { label: "On waking",
        ar: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
        tr: "Al-ḥamdu lillāhil-ladhī aḥyānā baʿda mā amātanā wa ilayhin-nushūr",
        en: "Praise be to Allah who gave us life after having caused us to die, and to Him is the resurrection.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "Before sleeping",
        ar: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
        tr: "Bismika Allāhumma amūtu wa aḥyā",
        en: "In Your name, O Allah, I die and I live.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "Leaving the home",
        ar: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
        tr: "Bismillāhi tawakkaltu ʿalallāh, wa lā ḥawla wa lā quwwata illā billāh",
        en: "In the name of Allah, I place my trust in Allah; there is no power and no strength except with Allah.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī" },
      { label: "Entering the home",
        ar: "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى رَبِّنَا تَوَكَّلْنَا",
        tr: "Bismillāhi walajnā wa bismillāhi kharajnā wa ʿalā Rabbinā tawakkalnā",
        en: "In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we place our trust.",
        src: "Sunan Abī Dāwūd" },
      { label: "Wearing new clothes",
        ar: "الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
        tr: "Al-ḥamdu lillāhil-ladhī kasānī hādhā wa razaqanīhi min ghayri ḥawlin minnī wa lā quwwah",
        en: "Praise be to Allah who has clothed me with this and provided it for me, with no power or strength of my own.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī" },
      { label: "Looking in the mirror",
        ar: "اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي",
        tr: "Allāhumma anta ḥassanta khalqī fa-ḥassin khuluqī",
        en: "O Allah, You have made my form good, so make my character good too.",
        src: "Musnad Aḥmad" },
    ]},

    { id: "food", title: "Food & Drink", icon: "cup", items: [
      { label: "Before eating",
        ar: "بِسْمِ اللَّهِ",
        tr: "Bismillāh",
        en: "In the name of Allah.",
        src: "Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim",
        note: "If forgotten at the start, say: Bismillāhi awwalahu wa ākhirahu." },
      { label: "After eating",
        ar: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
        tr: "Al-ḥamdu lillāhil-ladhī aṭʿamanī hādhā wa razaqanīhi min ghayri ḥawlin minnī wa lā quwwah",
        en: "Praise be to Allah who fed me this and provided it for me, with no power or ability of my own.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī" },
      { label: "Breaking a fast",
        ar: "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ",
        tr: "Dhahabaẓ-ẓama'u wabtallatil-ʿurūqu wa thabatal-ajru in shā'Allāh",
        en: "The thirst has gone, the veins are moistened, and the reward is certain, if Allah wills.",
        src: "Sunan Abī Dāwūd" },
      { label: "For the one who feeds you",
        ar: "اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي وَاسْقِ مَنْ سَقَانِي",
        tr: "Allāhumma aṭʿim man aṭʿamanī wasqi man saqānī",
        en: "O Allah, feed the one who fed me and give drink to the one who gave me drink.",
        src: "Ṣaḥīḥ Muslim" },
    ]},

    { id: "masjid", title: "Masjid & Ṣalāh", icon: "masjid", items: [
      { label: "Entering the masjid",
        ar: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
        tr: "Allāhummaf-taḥ lī abwāba raḥmatik",
        en: "O Allah, open for me the doors of Your mercy.",
        src: "Ṣaḥīḥ Muslim", note: "Enter with the right foot first." },
      { label: "Leaving the masjid",
        ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
        tr: "Allāhumma innī as'aluka min faḍlik",
        en: "O Allah, I ask You of Your bounty.",
        src: "Ṣaḥīḥ Muslim", note: "Leave with the left foot first." },
      { label: "After wuḍū'",
        ar: "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
        tr: "Ashhadu an lā ilāha illallāhu waḥdahu lā sharīka lah, wa ashhadu anna Muḥammadan ʿabduhu wa rasūluh",
        en: "I bear witness that there is no god but Allah alone, with no partner, and I bear witness that Muḥammad is His servant and Messenger.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "Hearing the adhān",
        ar: "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ",
        tr: "Allāhumma Rabba hādhihid-daʿwatit-tāmmah waṣ-ṣalātil-qā'imah, āti Muḥammadanil-wasīlata wal-faḍīlah, wabʿathhu maqāman maḥmūdanil-ladhī waʿadtah",
        en: "O Allah, Lord of this perfect call and the prayer to be established, grant Muḥammad the intercession and the excellence, and raise him to the praised station You have promised him.",
        src: "Ṣaḥīḥ al-Bukhārī", note: "Said after answering the adhān." },
      { label: "Entering the toilet",
        ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
        tr: "Allāhumma innī aʿūdhu bika minal-khubuthi wal-khabā'ith",
        en: "O Allah, I seek refuge in You from all evil and evil-doers.",
        src: "Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim" },
      { label: "Leaving the toilet",
        ar: "غُفْرَانَكَ",
        tr: "Ghufrānak",
        en: "I seek Your forgiveness.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī" },
    ]},

    { id: "hardship", title: "Worry & Hardship", icon: "heart", items: [
      { label: "In distress",
        ar: "لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ",
        tr: "Lā ilāha illallāhul-ʿAẓīmul-Ḥalīm, lā ilāha illallāhu Rabbul-ʿArshil-ʿAẓīm, lā ilāha illallāhu Rabbus-samāwāti wa Rabbul-arḍi wa Rabbul-ʿArshil-Karīm",
        en: "There is no god but Allah, the Mighty, the Forbearing. There is no god but Allah, Lord of the mighty Throne. There is no god but Allah, Lord of the heavens, Lord of the earth, and Lord of the noble Throne.",
        src: "Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim" },
      { label: "In anxiety and grief",
        ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
        tr: "Allāhumma innī aʿūdhu bika minal-hammi wal-ḥazan, wal-ʿajzi wal-kasal, wal-bukhli wal-jubn, wa ḍalaʿid-dayni wa ghalabatir-rijāl",
        en: "O Allah, I seek refuge in You from worry and grief, from incapacity and laziness, from miserliness and cowardice, from the burden of debt and from being overpowered by others.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "When something is difficult",
        ar: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا",
        tr: "Allāhumma lā sahla illā mā jaʿaltahu sahlā, wa anta tajʿalul-ḥazna idhā shi'ta sahlā",
        en: "O Allah, nothing is easy except what You make easy, and You make hardship easy if You wish.",
        src: "Ṣaḥīḥ Ibn Ḥibbān" },
      { label: "Anxiety over debt",
        ar: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
        tr: "Allāhummak-finī bi-ḥalālika ʿan ḥarāmik, wa aghninī bi-faḍlika ʿamman siwāk",
        en: "O Allah, suffice me with what You have made lawful against what You have forbidden, and enrich me by Your bounty so I need none but You.",
        src: "Jāmiʿ al-Tirmidhī" },
      { label: "Visiting the sick",
        ar: "لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ",
        tr: "Lā ba'sa ṭahūrun in shā'Allāh",
        en: "No harm, it is a purification, if Allah wills.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "Seeking forgiveness",
        ar: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
        tr: "Astaghfirullāhal-ʿAẓīmal-ladhī lā ilāha illā huwal-Ḥayyul-Qayyūmu wa atūbu ilayh",
        en: "I seek the forgiveness of Allah the Mighty, whom there is no god but He, the Ever-Living, the Sustainer, and I turn to Him in repentance.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī" },
    ]},

    { id: "travel", title: "Travel & Journey", icon: "road", items: [
      { label: "Boarding a vehicle",
        ar: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",
        tr: "Subḥānal-ladhī sakhkhara lanā hādhā wa mā kunnā lahu muqrinīn, wa innā ilā Rabbinā la-munqalibūn",
        en: "Glory to Him who has subjected this to us, when we could not have done it ourselves; and to our Lord we shall surely return.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī · az-Zukhruf 43:13–14" },
      { label: "Setting out on a journey",
        ar: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى، اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَذَا وَاطْوِ عَنَّا بُعْدَهُ",
        tr: "Allāhumma innā nas'aluka fī safarinā hādhal-birra wat-taqwā, wa minal-ʿamali mā tarḍā. Allāhumma hawwin ʿalaynā safaranā hādhā waṭwi ʿannā buʿdah",
        en: "O Allah, we ask You on this journey of ours for righteousness and piety, and for deeds that please You. O Allah, make this journey easy for us and fold up its distance.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "Arriving somewhere",
        ar: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
        tr: "Aʿūdhu bi-kalimātillāhit-tāmmāti min sharri mā khalaq",
        en: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "Returning home",
        ar: "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ",
        tr: "Āyibūna tā'ibūna ʿābidūna li-Rabbinā ḥāmidūn",
        en: "We return, repentant, worshipping and praising our Lord.",
        src: "Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim" },
    ]},

    { id: "people", title: "Family & Others", icon: "people", items: [
      { label: "For parents",
        ar: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
        tr: "Rabbir-ḥamhumā kamā rabbayānī ṣaghīrā",
        en: "My Lord, have mercy on them as they raised me when I was small.",
        src: "al-Isrā' 17:24" },
      { label: "Thanking someone",
        ar: "جَزَاكَ اللَّهُ خَيْرًا",
        tr: "Jazākallāhu khayrā",
        en: "May Allah reward you with good.",
        src: "Jāmiʿ al-Tirmidhī" },
      { label: "When someone sneezes",
        ar: "الْحَمْدُ لِلَّهِ — يَرْحَمُكَ اللَّهُ — يَهْدِيكُمُ اللَّهُ وَيُصْلِحُ بَالَكُمْ",
        tr: "Al-ḥamdu lillāh — yarḥamukallāh — yahdīkumullāhu wa yuṣliḥu bālakum",
        en: "The one who sneezes says “praise be to Allah”; the one who hears says “may Allah have mercy on you”; the first replies “may Allah guide you and set your affairs right”.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "Closing a gathering",
        ar: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ",
        tr: "Subḥānaka Allāhumma wa bi-ḥamdik, ashhadu an lā ilāha illā anta, astaghfiruka wa atūbu ilayk",
        en: "Glory be to You, O Allah, and praise. I bear witness that there is no god but You. I seek Your forgiveness and turn to You in repentance.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī",
        note: "Kaffārat al-majlis — an expiation for what was said in the gathering." },
      { label: "For knowledge",
        ar: "رَبِّ زِدْنِي عِلْمًا",
        tr: "Rabbi zidnī ʿilmā",
        en: "My Lord, increase me in knowledge.",
        src: "Ṭā Hā 20:114" },
      { label: "For good in both worlds",
        ar: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
        tr: "Rabbanā ātinā fid-dunyā ḥasanah, wa fil-ākhirati ḥasanah, wa qinā ʿadhāban-nār",
        en: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
        src: "al-Baqarah 2:201" },
    ]},

    { id: "weather", title: "Rain & Weather", icon: "cloud", items: [
      { label: "When it rains",
        ar: "اللَّهُمَّ صَيِّبًا نَافِعًا",
        tr: "Allāhumma ṣayyiban nāfiʿā",
        en: "O Allah, a beneficial downpour.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "After rainfall",
        ar: "مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ",
        tr: "Muṭirnā bi-faḍlillāhi wa raḥmatih",
        en: "We have been given rain by the bounty of Allah and His mercy.",
        src: "Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim" },
      { label: "On hearing thunder",
        ar: "سُبْحَانَ الَّذِي يُسَبِّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلَائِكَةُ مِنْ خِيفَتِهِ",
        tr: "Subḥānal-ladhī yusabbiḥur-raʿdu bi-ḥamdihi wal-malā'ikatu min khīfatih",
        en: "Glory to Him whom the thunder glorifies with praise, and the angels too, in awe of Him.",
        src: "al-Muwaṭṭa' · Mālik" },
      { label: "In strong wind",
        ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَأَعُوذُ بِكَ مِنْ شَرِّهَا",
        tr: "Allāhumma innī as'aluka khayrahā wa aʿūdhu bika min sharrihā",
        en: "O Allah, I ask You for its good and seek refuge in You from its evil.",
        src: "Sunan Abī Dāwūd · Ibn Mājah" },
    ]},

  ],
};
