/* Taiyabah Masjid — everyday duʿās
   Copyright (c) 2026 Yameen Bux. All rights reserved. See LICENSE.md.

   Built for someone learning: each duʿā carries the Arabic, a transliteration
   to read from until the Arabic is fluent, a plain English meaning, and the
   collection it comes from.

   Wording varies between narrations and printings. This set should be
   confirmed with the imam before it is treated as settled — the page says so.

   Loaded only when the Duʿās page is opened. */
window.DUAS = {
  reviewNote: "Wording varies between narrations and printings. Confirm with the imam before treating this as settled.",
  categories: [

    { id: "day", title: "Through the Day", icon: "sun", items: [
      { label: "On waking",
        ar: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
        tr: "Al-ḥamdu lillāhil-ladhī aḥyānā baʿda mā amātanā wa ilayhin-nushūr",
        en: "Praise be to Allah who gave us life after having caused us to die, and to Him is the resurrection.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "Before sleeping",
        ar: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
        tr: "Bismika Allāhumma amūtu wa aḥyā",
        en: "In Your name, O Allah, I die and I live.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "Leaving the home",
        ar: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
        tr: "Bismillāhi tawakkaltu ʿalallāh, wa lā ḥawla wa lā quwwata illā billāh",
        en: "In the name of Allah, I place my trust in Allah; there is no power and no strength except with Allah.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī" },
      { label: "Entering the home",
        ar: "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى رَبِّنَا تَوَكَّلْنَا",
        tr: "Bismillāhi walajnā wa bismillāhi kharajnā wa ʿalā Rabbinā tawakkalnā",
        en: "In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we place our trust.",
        src: "Sunan Abī Dāwūd" },
      { label: "Wearing new clothes",
        ar: "الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
        tr: "Al-ḥamdu lillāhil-ladhī kasānī hādhā wa razaqanīhi min ghayri ḥawlin minnī wa lā quwwah",
        en: "Praise be to Allah who has clothed me with this and provided it for me, with no power or strength of my own.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī" },
      { label: "Looking in the mirror",
        ar: "اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي",
        tr: "Allāhumma anta ḥassanta khalqī fa-ḥassin khuluqī",
        en: "O Allah, You have made my form good, so make my character good too.",
        src: "Musnad Aḥmad" },
      { label: "When you take your clothes off",
        ar: "بِسْمِ اللَّهِ",
        tr: "Bismillāh",
        en: "In the name of Allah.",
        note: "The same two words that open a meal, said here for a different moment. Tirmidhī records it and notes himself that the chain is not strong.",
        sameAs: "Before eating",
        src: "Jāmiʿ al-Tirmidhī" },
      { label: "Putting on a garment for the first time",
        ar: "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ كَسَوْتَنِيهِ أَسْأَلُكَ مِنْ خَيْرِهِ وَخَيْرِ مَا صُنِعَ لَهُ وَأَعُوذُ بِكَ مِنْ شَرِّهِ وَشَرِّ مَا صُنِعَ لَهُ",
        tr: "Allāhumma lakal-ḥamdu Anta kasawtanīh, as'aluka min khayrihi wa khayri mā ṣuniʿa lah, wa aʿūdhu bika min sharrihi wa sharri mā ṣuniʿa lah",
        en: "O Allah, all praise is Yours — You have clothed me with this. I ask You for its good and the good of what it was made for, and I seek refuge in You from its harm and the harm of what it was made for.",
        src: "Sunan Abī Dāwūd" },
    ]},

    { id: "food", title: "Food & Drink", icon: "cup", items: [
      { label: "Before eating",
        ar: "بِسْمِ اللَّهِ",
        tr: "Bismillāh",
        en: "In the name of Allah.",
        src: "Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim",
        note: "If forgotten at the start, say: Bismillāhi awwalahu wa ākhirahu." },
      { label: "After eating",
        ar: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
        tr: "Al-ḥamdu lillāhil-ladhī aṭʿamanī hādhā wa razaqanīhi min ghayri ḥawlin minnī wa lā quwwah",
        en: "Praise be to Allah who fed me this and provided it for me, with no power or ability of my own.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī" },
      { label: "Breaking a fast",
        ar: "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ",
        tr: "Dhahabaẓ-ẓama'u wabtallatil-ʿurūqu wa thabatal-ajru in shā'Allāh",
        en: "The thirst has gone, the veins are moistened, and the reward is certain, if Allah wills.",
        src: "Sunan Abī Dāwūd" },
      { label: "For the one who feeds you",
        ar: "اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي وَاسْقِ مَنْ سَقَانِي",
        tr: "Allāhumma aṭʿim man aṭʿamanī wasqi man saqānī",
        en: "O Allah, feed the one who fed me and give drink to the one who gave me drink.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "Over food or drink you are given",
        ar: "اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَأَطْعِمْنَا خَيْرًا مِنْهُ",
        tr: "Allāhumma bārik lanā fīhi wa aṭʿimnā khayran minh",
        en: "O Allah, bless it for us and feed us with better than it.",
        src: "Sunan Abī Dāwūd" },
      { label: "After drinking milk",
        ar: "اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَزِدْنَا مِنْهُ",
        tr: "Allāhumma bārik lanā fīhi wa zidnā minh",
        en: "O Allah, bless it for us and give us more of it.",
        note: "Milk alone has its own words: “give us more of it” rather than “better than it”.",
        src: "Sunan Abī Dāwūd" },
      { label: "For the household that fed you",
        ar: "أَفْطَرَ عِنْدَكُمُ الصَّائِمُونَ وَأَكَلَ طَعَامَكُمُ الأَبْرَارُ وَصَلَّتْ عَلَيْكُمُ الْمَلاَئِكَةُ",
        tr: "Afṭara ʿindakumuṣ-ṣā'imūn, wa akala ṭaʿāmakumul-abrār, wa ṣallat ʿalaykumul-malā'ikah",
        en: "May those who are fasting break their fast with you, may the righteous eat your food, and may the angels send blessings upon you.",
        note: "Said for your hosts. The Prophet ﷺ said it after eating at Saʿd ibn ʿUbādah's home.",
        src: "Sunan Abī Dāwūd" },
    ]},

    { id: "ramadan", title: "Ramadan", icon: "ramadan", items: [
      { label: "On sighting the new moon",
        ar: "اللَّهُمَّ أَهْلِلْهُ عَلَيْنَا بِالْيُمْنِ وَالإِيمَانِ وَالسَّلاَمَةِ وَالإِسْلاَمِ رَبِّي وَرَبُّكَ اللَّهُ",
        tr: "Allāhumma ahlilhu ʿalaynā bil-yumni wal-īmāni was-salāmati wal-islām. Rabbī wa Rabbukallāh",
        en: "O Allah, bring it over us with blessing and faith, with safety and with Islam. My Lord and your Lord is Allah.",
        note: "Said on first seeing the crescent — of Ramaḍān or of any month.",
        src: "Jāmiʿ al-Tirmidhī" },
      { label: "When someone picks a fight while you are fasting",
        ar: "إِنِّي صَائِمٌ",
        tr: "Innī ṣā'im",
        en: "I am fasting.",
        note: "Said twice, and out loud. The fast is a shield: it is not answered in kind.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "On Laylat al-Qadr",
        ar: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
        tr: "Allāhumma innaka ʿafuwwun tuḥibbul-ʿafwa faʿfu ʿannī",
        en: "O Allah, You are most forgiving, and You love to forgive, so forgive me.",
        note: "ʿĀ'ishah asked what to say if she found Laylat al-Qadr. Jāmiʿ al-Tirmidhī records the same duʿā with “ʿafuwwun karīm”.",
        src: "Sunan Ibn Mājah" },
      { label: "Asking as you break your fast",
        ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ بِرَحْمَتِكَ الَّتِي وَسِعَتْ كُلَّ شَىْءٍ أَنْ تَغْفِرَ لِي",
        tr: "Allāhumma innī as'aluka bi-raḥmatikal-latī wasiʿat kulla shay'in an taghfira lī",
        en: "O Allah, I ask You, by Your mercy that encompasses all things, to forgive me.",
        note: "ʿAbdullāh ibn ʿAmr said this at ifṭār. In the same report: the fasting person has a duʿā at breaking the fast that is not turned away.",
        src: "Sunan Ibn Mājah" },
    ]},

    { id: "masjid", title: "Masjid & Ṣalāh", icon: "masjid", items: [
      { label: "Entering the masjid",
        ar: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
        tr: "Allāhummaf-taḥ lī abwāba raḥmatik",
        en: "O Allah, open for me the doors of Your mercy.",
        src: "Ṣaḥīḥ Muslim", note: "Enter with the right foot first." },
      { label: "Leaving the masjid",
        ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
        tr: "Allāhumma innī as'aluka min faḍlik",
        en: "O Allah, I ask You of Your bounty.",
        src: "Ṣaḥīḥ Muslim", note: "Leave with the left foot first." },
      { label: "After wuḍū'",
        ar: "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
        tr: "Ashhadu an lā ilāha illallāhu waḥdahu lā sharīka lah, wa ashhadu anna Muḥammadan ʿabduhu wa rasūluh",
        en: "I bear witness that there is no god but Allah alone, with no partner, and I bear witness that Muḥammad is His servant and Messenger.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "Hearing the adhān",
        ar: "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ",
        tr: "Allāhumma Rabba hādhihid-daʿwatit-tāmmah waṣ-ṣalātil-qā'imah, āti Muḥammadanil-wasīlata wal-faḍīlah, wabʿathhu maqāman maḥmūdanil-ladhī waʿadtah",
        en: "O Allah, Lord of this perfect call and the prayer to be established, grant Muḥammad the intercession and the excellence, and raise him to the praised station You have promised him.",
        src: "Ṣaḥīḥ al-Bukhārī", note: "Said after answering the adhān." },
      { label: "Entering the toilet",
        ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
        tr: "Allāhumma innī aʿūdhu bika minal-khubuthi wal-khabā'ith",
        en: "O Allah, I seek refuge in You from all evil and evil-doers.",
        src: "Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim" },
      { label: "Leaving the toilet",
        ar: "غُفْرَانَكَ",
        tr: "Ghufrānak",
        en: "I seek Your forgiveness.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī" },
    ]},

    { id: "hardship", title: "Worry & Hardship", icon: "heart", items: [
      { label: "In distress",
        ar: "لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ",
        tr: "Lā ilāha illallāhul-ʿAẓīmul-Ḥalīm, lā ilāha illallāhu Rabbul-ʿArshil-ʿAẓīm, lā ilāha illallāhu Rabbus-samāwāti wa Rabbul-arḍi wa Rabbul-ʿArshil-Karīm",
        en: "There is no god but Allah, the Mighty, the Forbearing. There is no god but Allah, Lord of the mighty Throne. There is no god but Allah, Lord of the heavens, Lord of the earth, and Lord of the noble Throne.",
        src: "Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim" },
      { label: "In anxiety and grief",
        ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
        tr: "Allāhumma innī aʿūdhu bika minal-hammi wal-ḥazan, wal-ʿajzi wal-kasal, wal-bukhli wal-jubn, wa ḍalaʿid-dayni wa ghalabatir-rijāl",
        en: "O Allah, I seek refuge in You from worry and grief, from incapacity and laziness, from miserliness and cowardice, from the burden of debt and from being overpowered by others.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "When something is difficult",
        ar: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا",
        tr: "Allāhumma lā sahla illā mā jaʿaltahu sahlā, wa anta tajʿalul-ḥazna idhā shi'ta sahlā",
        en: "O Allah, nothing is easy except what You make easy, and You make hardship easy if You wish.",
        src: "Ṣaḥīḥ Ibn Ḥibbān" },
      { label: "Anxiety over debt",
        ar: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
        tr: "Allāhummak-finī bi-ḥalālika ʿan ḥarāmik, wa aghninī bi-faḍlika ʿamman siwāk",
        en: "O Allah, suffice me with what You have made lawful against what You have forbidden, and enrich me by Your bounty so I need none but You.",
        src: "Jāmiʿ al-Tirmidhī" },
      { label: "Visiting the sick",
        ar: "لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ",
        tr: "Lā ba'sa ṭahūrun in shā'Allāh",
        en: "No harm, it is a purification, if Allah wills.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "Seeking forgiveness",
        ar: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
        tr: "Astaghfirullāhal-ʿAẓīmal-ladhī lā ilāha illā huwal-Ḥayyul-Qayyūmu wa atūbu ilayh",
        en: "I seek the forgiveness of Allah the Mighty, whom there is no god but He, the Ever-Living, the Sustainer, and I turn to Him in repentance.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī" },
      { label: "When something frightens you",
        ar: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ غَضَبِهِ وَشَرِّ عِبَادِهِ وَمِنْ هَمَزَاتِ الشَّيَاطِينِ وَأَنْ يَحْضُرُونِ",
        tr: "Aʿūdhu bi-kalimātillāhit-tāmmati min ghaḍabihi wa sharri ʿibādihi wa min hamazātish-shayāṭīni wa an yaḥḍurūn",
        en: "I seek refuge in the perfect words of Allah from His anger, from the evil of His servants, from the promptings of the devils, and from their coming near me.",
        note: "The Prophet ﷺ taught these words to his companions for moments of fright.",
        src: "Sunan Abī Dāwūd" },
    ]},

    { id: "health", title: "Health & Healing", icon: "health", items: [
      { label: "When you feel pain",
        ar: "بِاسْمِ اللَّهِ أَعُوذُ بِاللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ",
        tr: "Bismillāh. Aʿūdhu billāhi wa qudratihi min sharri mā ajidu wa uḥādhir",
        en: "In the name of Allah. I seek refuge in Allah and in His power from the evil of what I find and what I fear.",
        note: "Place your hand where it hurts. Say “Bismillāh” three times, then the rest seven times.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "Praying over someone who is ill",
        ar: "أَذْهِبِ الْبَاسَ رَبَّ النَّاسِ اشْفِ أَنْتَ الشَّافِي لاَ شِفَاءَ إِلاَّ شِفَاؤُكَ شِفَاءً لاَ يُغَادِرُ سَقَمًا",
        tr: "Adhhibil-bāsa Rabban-nās, ishfi Antash-Shāfī, lā shifā'a illā shifā'uk, shifā'an lā yughādiru saqamā",
        en: "Take away the harm, Lord of mankind, and heal — You are the Healer. There is no healing but Your healing, a healing that leaves no illness behind.",
        src: "Sunan Abī Dāwūd" },
      { label: "For health and well-being",
        ar: "اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي لاَ إِلَهَ إِلاَّ أَنْتَ",
        tr: "Allāhumma ʿāfinī fī badanī, Allāhumma ʿāfinī fī samʿī, Allāhumma ʿāfinī fī baṣarī, lā ilāha illā Ant",
        en: "O Allah, grant me well-being in my body. O Allah, grant me well-being in my hearing. O Allah, grant me well-being in my sight. There is no god but You.",
        note: "Said three times in the morning and three times in the evening.",
        src: "Sunan Abī Dāwūd" },
    ]},

    { id: "travel", title: "Travel & Journey", icon: "road", items: [
      { label: "Boarding a vehicle",
        ar: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",
        tr: "Subḥānal-ladhī sakhkhara lanā hādhā wa mā kunnā lahu muqrinīn, wa innā ilā Rabbinā la-munqalibūn",
        en: "Glory to Him who has subjected this to us, when we could not have done it ourselves; and to our Lord we shall surely return.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī · az-Zukhruf 43:13–14" },
      { label: "Setting out on a journey",
        ar: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى، اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَذَا وَاطْوِ عَنَّا بُعْدَهُ",
        tr: "Allāhumma innā nas'aluka fī safarinā hādhal-birra wat-taqwā, wa minal-ʿamali mā tarḍā. Allāhumma hawwin ʿalaynā safaranā hādhā waṭwi ʿannā buʿdah",
        en: "O Allah, we ask You on this journey of ours for righteousness and piety, and for deeds that please You. O Allah, make this journey easy for us and fold up its distance.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "Arriving somewhere",
        ar: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
        tr: "Aʿūdhu bi-kalimātillāhit-tāmmāti min sharri mā khalaq",
        en: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "Returning home",
        ar: "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ",
        tr: "Āyibūna tā'ibūna ʿābidūna li-Rabbinā ḥāmidūn",
        en: "We return, repentant, worshipping and praising our Lord.",
        src: "Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim" },
    ]},

    { id: "people", title: "Family & Others", icon: "people", items: [
      { label: "For parents",
        ar: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
        tr: "Rabbir-ḥamhumā kamā rabbayānī ṣaghīrā",
        en: "My Lord, have mercy on them as they raised me when I was small.",
        src: "al-Isrā' 17:24" },
      { label: "Thanking someone",
        ar: "جَزَاكَ اللَّهُ خَيْرًا",
        tr: "Jazākallāhu khayrā",
        en: "May Allah reward you with good.",
        src: "Jāmiʿ al-Tirmidhī" },
      { label: "When someone sneezes",
        ar: "الْحَمْدُ لِلَّهِ — يَرْحَمُكَ اللَّهُ — يَهْدِيكُمُ اللَّهُ وَيُصْلِحُ بَالَكُمْ",
        tr: "Al-ḥamdu lillāh — yarḥamukallāh — yahdīkumullāhu wa yuṣliḥu bālakum",
        en: "The one who sneezes says “praise be to Allah”; the one who hears says “may Allah have mercy on you”; the first replies “may Allah guide you and set your affairs right”.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "Closing a gathering",
        ar: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ",
        tr: "Subḥānaka Allāhumma wa bi-ḥamdik, ashhadu an lā ilāha illā anta, astaghfiruka wa atūbu ilayk",
        en: "Glory be to You, O Allah, and praise. I bear witness that there is no god but You. I seek Your forgiveness and turn to You in repentance.",
        src: "Sunan Abī Dāwūd · Jāmiʿ al-Tirmidhī",
        note: "Kaffārat al-majlis — an expiation for what was said in the gathering." },
      { label: "For knowledge",
        ar: "رَبِّ زِدْنِي عِلْمًا",
        tr: "Rabbi zidnī ʿilmā",
        en: "My Lord, increase me in knowledge.",
        src: "Ṭā Hā 20:114" },
      { label: "For good in both worlds",
        ar: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
        tr: "Rabbanā ātinā fid-dunyā ḥasanah, wa fil-ākhirati ḥasanah, wa qinā ʿadhāban-nār",
        en: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
        src: "al-Baqarah 2:201" },
      { label: "For someone wearing new clothes",
        ar: "تُبْلِي وَيُخْلِفُ اللَّهُ تَعَالَى",
        tr: "Tublī wa yukhlifullāhu taʿālā",
        en: "May you wear it out, and may Allah give you another in its place.",
        note: "What the Companions said to one another on seeing a new garment.",
        src: "Sunan Abī Dāwūd" },
    ]},

    { id: "marriage", title: "Marriage & Children", icon: "marriage", items: [
      { label: "Congratulating a newly-married couple",
        ar: "بَارَكَ اللَّهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ",
        tr: "Bārakallāhu laka wa bāraka ʿalayka wa jamaʿa baynakumā fī khayr",
        en: "May Allah bless you, and send blessings upon you, and join you together in goodness.",
        src: "Sunan Abī Dāwūd" },
      { label: "When you marry",
        ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَخَيْرَ مَا جَبَلْتَهَا عَلَيْهِ وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَمِنْ شَرِّ مَا جَبَلْتَهَا عَلَيْهِ",
        tr: "Allāhumma innī as'aluka khayrahā wa khayra mā jabaltahā ʿalayh, wa aʿūdhu bika min sharrihā wa min sharri mā jabaltahā ʿalayh",
        en: "O Allah, I ask You for the good in her and the good of what You have made her inclined towards, and I seek refuge in You from the evil in her and the evil of what You have made her inclined towards.",
        note: "Said on marrying. A wife says the same, changing the pronouns.",
        src: "Sunan Abī Dāwūd" },
      { label: "Before a husband and wife come together",
        ar: "بِسْمِ اللَّهِ اللَّهُمَّ جَنِّبْنَا الشَّيْطَانَ وَجَنِّبِ الشَّيْطَانَ مَا رَزَقْتَنَا",
        tr: "Bismillāh. Allāhumma jannibnash-shayṭāna wa jannibish-shayṭāna mā razaqtanā",
        en: "In the name of Allah. O Allah, keep the devil away from us, and keep the devil away from what You grant us.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "Seeking Allah's protection for your children",
        ar: "أُعِيذُكُمَا بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لاَمَّةٍ",
        tr: "Uʿīdhukumā bi-kalimātillāhit-tāmmati min kulli shayṭānin wa hāmmah, wa min kulli ʿaynin lāmmah",
        en: "I place you both in the protection of the perfect words of Allah, from every devil and every creeping thing, and from every harmful eye.",
        note: "The Prophet ﷺ said this over Ḥasan and Ḥusayn. For one child, say “Uʿīdhuka”.",
        src: "Sunan Abī Dāwūd" },
    ]},

    { id: "death", title: "Death & Loss", icon: "death", items: [
      { label: "When you hear bad news or suffer a loss",
        ar: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا",
        tr: "Innā lillāhi wa innā ilayhi rājiʿūn. Allāhumma'jurnī fī muṣībatī wa akhlif lī khayran minhā",
        en: "To Allah we belong and to Him we return. O Allah, reward me in my affliction and give me something better than it in its place.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "For someone who has died",
        ar: "اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ وَعَافِهِ وَاعْفُ عَنْهُ وَأَكْرِمْ نُزُلَهُ وَوَسِّعْ مُدْخَلَهُ وَاغْسِلْهُ بِالْمَاءِ وَالثَّلْجِ وَالْبَرَدِ وَنَقِّهِ مِنَ الْخَطَايَا كَمَا نَقَّيْتَ الثَّوْبَ الأَبْيَضَ مِنَ الدَّنَسِ وَأَبْدِلْهُ دَارًا خَيْرًا مِنْ دَارِهِ وَأَهْلاً خَيْرًا مِنْ أَهْلِهِ وَزَوْجًا خَيْرًا مِنْ زَوْجِهِ وَأَدْخِلْهُ الْجَنَّةَ وَأَعِذْهُ مِنْ عَذَابِ الْقَبْرِ أَوْ مِنْ عَذَابِ النَّارِ",
        tr: "Allāhumma-ghfir lahu warḥamhu wa ʿāfihi waʿfu ʿanhu, wa akrim nuzulahu wa wassiʿ mudkhalahu, waghsilhu bil-mā'i wath-thalji wal-barad, wa naqqihi minal-khaṭāyā kamā naqqaytath-thawbal-abyaḍa minad-danas, wa abdilhu dāran khayran min dārihi wa ahlan khayran min ahlihi wa zawjan khayran min zawjihi, wa adkhilhul-jannah, wa aʿidhhu min ʿadhābil-qabri aw min ʿadhābin-nār",
        en: "O Allah, forgive him and have mercy on him, keep him safe and pardon him, honour his arrival and make his entry wide. Wash him with water, snow and hail, and cleanse him of his sins as a white garment is cleansed of dirt. Give him a home better than his home, a family better than his family and a spouse better than his spouse. Admit him into the Garden, and protect him from the punishment of the grave and the punishment of the Fire.",
        note: "The duʿā of the funeral prayer. For a woman, the pronouns change.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "When visiting the graveyard",
        ar: "السَّلاَمُ عَلَيْكُمْ أَهْلَ الدِّيَارِ مِنَ الْمُؤْمِنِينَ وَالْمُسْلِمِينَ وَإِنَّا إِنْ شَاءَ اللَّهُ لَلَاحِقُونَ أَسْأَلُ اللَّهَ لَنَا وَلَكُمْ الْعَافِيَةَ",
        tr: "As-salāmu ʿalaykum ahlad-diyāri minal-mu'minīna wal-muslimīn, wa innā in shā'Allāhu la-lāḥiqūn. As'alullāha lanā wa lakumul-ʿāfiyah",
        en: "Peace be upon you, people of these dwellings, believers and Muslims. We will, if Allah wills, be joining you. I ask Allah for well-being for us and for you.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "Comforting someone bereaved",
        ar: "إِنَّ لِلَّهِ مَا أَخَذَ وَلَهُ مَا أَعْطَى وَكُلُّ شَىْءٍ عِنْدَهُ بِأَجَلٍ مُسَمًّى فَلْتَصْبِرْ وَلْتَحْتَسِبْ",
        tr: "Inna lillāhi mā akhadha wa lahu mā aʿṭā, wa kullu shay'in ʿindahu bi-ajalin musammā — fal-taṣbir wal-taḥtasib",
        en: "To Allah belongs what He has taken, and to Him belongs what He has given, and everything with Him has an appointed term. So be patient, and seek the reward.",
        src: "Ṣaḥīḥ Muslim" },
      { label: "At the graveside after burial",
        ar: "اسْتَغْفِرُوا لأَخِيكُمْ وَسَلُوا لَهُ التَّثْبِيتَ فَإِنَّهُ الآنَ يُسْأَلُ",
        tr: "Istaghfirū li-akhīkum wa salū lahut-tathbīt, fa-innahul-āna yus'al",
        en: "Ask forgiveness for your brother, and ask that he be made firm — for he is being questioned now.",
        note: "Not a set formula. The Prophet ﷺ would stand at the grave once the burial was done and tell those present to do this.",
        src: "Sunan Abī Dāwūd" },
    ]},

    { id: "weather", title: "Rain & Weather", icon: "cloud", items: [
      { label: "When it rains",
        ar: "اللَّهُمَّ صَيِّبًا نَافِعًا",
        tr: "Allāhumma ṣayyiban nāfiʿā",
        en: "O Allah, a beneficial downpour.",
        src: "Ṣaḥīḥ al-Bukhārī" },
      { label: "After rainfall",
        ar: "مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ",
        tr: "Muṭirnā bi-faḍlillāhi wa raḥmatih",
        en: "We have been given rain by the bounty of Allah and His mercy.",
        src: "Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim" },
      { label: "On hearing thunder",
        ar: "سُبْحَانَ الَّذِي يُسَبِّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلَائِكَةُ مِنْ خِيفَتِهِ",
        tr: "Subḥānal-ladhī yusabbiḥur-raʿdu bi-ḥamdihi wal-malā'ikatu min khīfatih",
        en: "Glory to Him whom the thunder glorifies with praise, and the angels too, in awe of Him.",
        src: "al-Muwaṭṭa' · Mālik" },
      { label: "In strong wind",
        ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَأَعُوذُ بِكَ مِنْ شَرِّهَا",
        tr: "Allāhumma innī as'aluka khayrahā wa aʿūdhu bika min sharrihā",
        en: "O Allah, I ask You for its good and seek refuge in You from its evil.",
        src: "Sunan Abī Dāwūd · Ibn Mājah" },
    ]},

    /* From the Qurʼan — the supplications the prophets made, in the words the
       Qurʼan gives them. Distinct from the 40 Rabbanā, which are the plural
       رَبَّنَا duʿās; these are the singular ones.

       NO TRANSLITERATION, deliberately. The Adhkār does the same with its
       Qurʼanic passages: inventing a pronunciation guide for scripture adds
       a layer nobody verified. The renderer omits the line when it is absent.

       The Arabic is NOT typed. It is lifted word-for-word out of the verified
       sūrah files by scripts/build-quran-duas.mjs and held there by
       scripts/verify-quran-duas.mjs. Never hand-edit the ar: lines — change
       the span in the builder and regenerate. */
    { id: "quran", title: "From the Qurʼan", icon: "quran", items: [
      { label: "The duʿā of Yūnus",
        ar: "لَا٘ اِلٰهَ اِلَّا٘ اَنۡتَ سُبۡحٰنَكَ اِنِّيۡ كُنۡتُ مِنَ الظّٰلِمِيۡنَ",
        en: "There is no god but You. Glory be to You. I have surely been among the wrongdoers.",
        src: "Sūrah al-Anbiyā' 21:87" },
      { label: "Before studying",
        ar: "رَبِّ زِدۡنِيۡ عِلۡمًا",
        en: "My Lord, increase me in knowledge.",
        src: "Sūrah Ṭā Hā 20:114" },
      { label: "Before speaking",
        ar: "رَبِّ اشۡرَحۡ لِيۡ صَدۡرِيۡ وَيَسِّرۡ لِيۡ٘ اَمۡرِيۡ",
        en: "My Lord, expand my breast for me, and make my task easy for me.",
        src: "Sūrah Ṭā Hā 20:25–26" },
      { label: "To be steadfast in prayer",
        ar: "رَبِّ اجۡعَلۡنِيۡ مُقِيۡمَ الصَّلٰوةِ وَمِنۡ ذُرِّيَّتِيۡ",
        en: "My Lord, make me one who establishes prayer, and my offspring too.",
        src: "Sūrah Ibrāhīm 14:40" },
      { label: "For righteous children",
        ar: "رَبِّ هَبۡ لِيۡ مِنَ الصّٰلِحِيۡنَ",
        en: "My Lord, grant me one of the righteous.",
        src: "Sūrah aṣ-Ṣāffāt 37:100" },
      { label: "When childless",
        ar: "رَبِّ لَا تَذَرۡنِيۡ فَرۡدًا وَّاَنۡتَ خَيۡرُ الۡوٰرِثِيۡنَ",
        en: "My Lord, do not leave me alone, and You are the best of inheritors.",
        src: "Sūrah al-Anbiyā' 21:89" },
      { label: "Forgiveness for one's parents",
        ar: "رَبِّ اغۡفِرۡ لِيۡ وَلِوَالِدَيَّ",
        en: "My Lord, forgive me and my parents.",
        src: "Sūrah Nūḥ 71:28" },
      { label: "Asking for mercy",
        ar: "رَبِّ اغۡفِرۡ وَارۡحَمۡ وَاَنۡتَ خَيۡرُ الرّٰحِمِيۡنَ",
        en: "My Lord, forgive and have mercy, for You are the best of those who show mercy.",
        src: "Sūrah al-Mu'minūn 23:118" },
      { label: "When afraid",
        ar: "حَسۡبُنَا اللّٰهُ وَنِعۡمَ الۡوَكِيۡلُ",
        en: "Allah is sufficient for us, and He is the best disposer of affairs.",
        src: "Sūrah Āl ʿImrān 3:173" },
      { label: "Placing your trust",
        ar: "حَسۡبِيَ اللّٰهُ لَا٘ اِلٰهَ اِلَّا هُوَ عَلَيۡهِ تَوَكَّلۡتُ وَهُوَ رَبُّ الۡعَرۡشِ الۡعَظِيۡمِ",
        en: "Allah is sufficient for me. There is no god but He. In Him I place my trust, and He is the Lord of the Mighty Throne.",
        src: "Sūrah at-Tawbah 9:129" },
      { label: "Setting out with sincerity",
        ar: "رَبِّ اَدۡخِلۡنِيۡ مُدۡخَلَ صِدۡقٍ وَّاَخۡرِجۡنِيۡ مُخۡرَجَ صِدۡقٍ وَّاجۡعَلۡ لِّيۡ مِنۡ لَّدُنۡكَ سُلۡطٰنًا نَّصِيۡرًا",
        en: "My Lord, cause me to enter by a truthful entrance and to leave by a truthful exit, and grant me from Yourself a helping authority.",
        src: "Sūrah al-Isrā' 17:80" },
      { label: "In illness",
        ar: "اَنِّيۡ مَسَّنِيَ الضُّرُّ وَاَنۡتَ اَرۡحَمُ الرّٰحِمِيۡنَ",
        en: "Affliction has touched me, and You are the most merciful of those who show mercy.",
        src: "Sūrah al-Anbiyā' 21:83" },
      { label: "For wisdom and good company",
        ar: "رَبِّ هَبۡ لِيۡ حُكۡمًا وَّاَلۡحِقۡنِيۡ بِالصّٰلِحِيۡنَ",
        en: "My Lord, grant me wisdom and join me with the righteous.",
        src: "Sūrah ash-Shuʿarā' 26:83" },
      { label: "When in need",
        ar: "رَبِّ اِنِّيۡ لِمَا٘ اَنۡزَلۡتَ اِلَيَّ مِنۡ خَيۡرٍ فَقِيۡرٌ",
        en: "My Lord, I am in need of whatever good You send down to me.",
        src: "Sūrah al-Qaṣaṣ 28:24" },
      { label: "For yourself and your family",
        ar: "رَبِّ اغۡفِرۡ لِيۡ وَلِاَخِيۡ وَاَدۡخِلۡنَا فِيۡ رَحۡمَتِكَ وَاَنۡتَ اَرۡحَمُ الرّٰحِمِيۡنَ",
        en: "My Lord, forgive me and my brother, and admit us into Your mercy, for You are the most merciful of those who show mercy.",
        src: "Sūrah al-Aʿrāf 7:151" },
      { label: "For Paradise",
        ar: "وَاجۡعَلۡنِيۡ مِنۡ وَّرَثَةِ جَنَّةِ النَّعِيۡمِ",
        en: "And make me among the inheritors of the Garden of Delight.",
        src: "Sūrah ash-Shuʿarā' 26:85" },
      { label: "Gratitude, and for one's children",
        ar: "رَبِّ اَوۡزِعۡنِيۡ٘ اَنۡ اَشۡكُرَ نِعۡمَتَكَ الَّتِيۡ٘ اَنۡعَمۡتَ عَلَيَّ وَعَلٰي وَالِدَيَّ وَاَنۡ اَعۡمَلَ صَالِحًا تَرۡضٰىهُ وَاَصۡلِحۡ لِيۡ فِيۡ ذُرِّيَّتِيۡ اِنِّيۡ تُبۡتُ اِلَيۡكَ وَاِنِّيۡ مِنَ الۡمُسۡلِمِيۡنَ",
        en: "My Lord, enable me to be grateful for Your favour which You have bestowed upon me and upon my parents, and to do righteous deeds that please You, and make my offspring righteous for me. I turn to You in repentance, and I am of those who submit.",
        src: "Sūrah al-Aḥqāf 46:15" },
    ]},


  ],
};
